In [1]:
import os

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import pandas as pd

d = pd.read_csv("data/clean_data.csv")

print(type(d))
print(d.shape)
print(d.head())

<class 'pandas.DataFrame'>
(100000, 22)
   rcount gender  dialysisrenalendstage  asthma  irondef  pneum  \
0     0.0      F                      0       0        0      0
1     0.0      F                      0       0        0      0
2     1.0      F                      0       0        0      0
3     0.0      F                      0       0        0      0
4     0.0      F                      0       0        0      1

   substancedependence  psychologicaldisordermajor  depress  psychother  ...  \
0                    0                           0        0           0  ...
1                    0                           0        0           0  ...
2                    0                           0        0           0  ...
3                    0                           0        0           0  ...
4                    0                           1        0           0  ...

   hemo  bloodureanitro  pulse  secondarydiagnosisnonicd9  facid  \
0     0            12.0     96                          4      B
1     0             8.0     61                          1      A
2     0            12.0     64                          2      B
3     0            12.0     76                          1      A
4     0            11.5     67                          2      E

   lengthofstay comorbidity_score  metabolic_stress_index  \
0             3                 0               92.838049
1             7                 0                9.189801
2             3                 0               37.472010
3             1                 0               64.383005
4             4                 2                6.478510

   bun_creatinine_ratio  bmi_category
0              8.628548         obese
1              8.481995    overweight
2             11.259568    overweight
3             13.232300    overweight
4              9.252821         obese

[5 rows x 22 columns]

In [4]:
d

,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,...,hemo,bloodureanitro,pulse,secondarydiagnosisnonicd9,facid,lengthofstay,comorbidity_score,metabolic_stress_index,bun_creatinine_ratio,bmi_category
0,0.0,F,0,0,0,0,0,0,0,0,...,0,12.0,96,4,B,3,0,92.838049,8.628548,obese
1,0.0,F,0,0,0,0,0,0,0,0,...,0,8.0,61,1,A,7,0,9.189801,8.481995,overweight
2,1.0,F,0,0,0,0,0,0,0,0,...,0,12.0,64,2,B,3,0,37.472010,11.259568,overweight
3,0.0,F,0,0,0,0,0,0,0,0,...,0,12.0,76,1,A,1,0,64.383005,13.232300,overweight
4,0.0,F,0,0,0,1,0,1,0,0,...,0,11.5,67,2,E,4,2,6.478510,9.252821,obese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,3.0,M,0,0,0,0,0,0,0,0,...,0,12.0,80,1,B,6,0,78.807578,18.452075,obese
99996,0.0,M,0,0,0,0,0,0,0,0,...,0,12.0,61,1,B,1,0,24.015130,7.887296,overweight
99997,1.0,M,0,0,1,0,0,0,0,0,...,0,12.0,61,1,C,4,1,11.592201,11.699474,overweight
99998,0.0,M,0,0,0,0,0,0,1,0,...,0,16.0,59,1,B,4,1,15.770215,15.452821,overweight
99999,0.0,F,0,0,0,0,0,0,0,0,...,0,12.0,74,4,B,2,0,50.522342,14.759897,overweight

In [5]:
d['gender'] = d['gender'].map({'M': 1, 'F': 0})
d.drop(columns=['facid'],inplace=True, errors='ignore')

In [6]:
d['bmi_category'].value_counts()

bmi_category
overweight    53152
obese         46042
normal          806
Name: count, dtype: int64

In [21]:
for col in d.select_dtypes(include='float').columns:
    d[col] = d[col].fillna(0).astype(int)
d.drop(columns=['bmi_category'],inplace=True, errors='ignore')

In [22]:
from sklearn.model_selection import train_test_split

X = d.drop(columns=["lengthofstay"])
y = d["lengthofstay"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [23]:
X.head()

,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,malnutrition,hemo,bloodureanitro,pulse,secondarydiagnosisnonicd9,comorbidity_score,metabolic_stress_index,bun_creatinine_ratio
0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,96,4,0,92,8
1,0,0,0,0,0,0,0,0,0,0,0,0,0,8,61,1,0,9,8
2,1,0,0,0,0,0,0,0,0,0,0,0,0,12,64,2,0,37,11
3,0,0,0,0,0,0,0,0,0,0,0,0,0,12,76,1,0,64,13
4,0,0,0,0,0,1,0,1,0,0,0,0,0,11,67,2,2,6,9

In [ ]:
# d.drop(columns=['bmi_category'],inplace=True, errors='ignore')

In [24]:
d

,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,malnutrition,hemo,bloodureanitro,pulse,secondarydiagnosisnonicd9,lengthofstay,comorbidity_score,metabolic_stress_index,bun_creatinine_ratio
0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,96,4,3,0,92,8
1,0,0,0,0,0,0,0,0,0,0,0,0,0,8,61,1,7,0,9,8
2,1,0,0,0,0,0,0,0,0,0,0,0,0,12,64,2,3,0,37,11
3,0,0,0,0,0,0,0,0,0,0,0,0,0,12,76,1,1,0,64,13
4,0,0,0,0,0,1,0,1,0,0,0,0,0,11,67,2,4,2,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,3,1,0,0,0,0,0,0,0,0,0,0,0,12,80,1,6,0,78,18
99996,0,1,0,0,0,0,0,0,0,0,0,0,0,12,61,1,1,0,24,7
99997,1,1,0,0,1,0,0,0,0,0,0,0,0,12,61,1,4,1,11,11
99998,0,1,0,0,0,0,0,0,1,0,0,0,0,16,59,1,4,1,15,15
99999,0,0,0,0,0,0,0,0,0,0,0,0,0,12,74,4,2,0,50,14

In [25]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   rcount                      100000 non-null  int64
 1   gender                      100000 non-null  int64
 2   dialysisrenalendstage       100000 non-null  int64
 3   asthma                      100000 non-null  int64
 4   irondef                     100000 non-null  int64
 5   pneum                       100000 non-null  int64
 6   substancedependence         100000 non-null  int64
 7   psychologicaldisordermajor  100000 non-null  int64
 8   depress                     100000 non-null  int64
 9   psychother                  100000 non-null  int64
 10  fibrosisandother            100000 non-null  int64
 11  malnutrition                100000 non-null  int64
 12  hemo                        100000 non-null  int64
 13  bloodureanitro              100000 non-null  int64
 14  pulse                       100000 non-null  int64
 15  secondarydiagnosisnonicd9   100000 non-null  int64
 16  lengthofstay                100000 non-null  int64
 17  comorbidity_score           100000 non-null  int64
 18  metabolic_stress_index      100000 non-null  int64
 19  bun_creatinine_ratio        100000 non-null  int64
dtypes: int64(20)
memory usage: 15.3 MB

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

model = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred))

In [27]:
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

model = XGBRegressor(objective="reg:squarederror", random_state=42, n_jobs=-1)

param_dist = {
    "n_estimators": [200, 300, 500, 700],
    "max_depth": [3, 4, 5, 6, 8],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "subsample": [0.7, 0.8, 0.9, 1.0],
    "colsample_bytree": [0.7, 0.8, 0.9, 1.0],
    "gamma": [0, 0.1, 0.2, 0.3],
    "reg_alpha": [0, 0.01, 0.1, 1],
    "reg_lambda": [1, 1.5, 2, 3]
}

search = RandomizedSearchCV(
    model,
    param_distributions=param_dist,
    n_iter=20,
    scoring="r2",
    cv=3,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

best_model = search.best_estimator_

y_pred = best_model.predict(X_test)

print("Best Params:", search.best_params_)
print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred))

Fitting 3 folds for each of 20 candidates, totalling 60 fits
Best Params: {'subsample': 1.0, 'reg_lambda': 1.5, 'reg_alpha': 0.1, 'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.2, 'gamma': 0.3, 'colsample_bytree': 0.9}
R2: 0.5833203792572021
MAE: 1.0041413307189941
RMSE: 2.286402940750122

In [28]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(random_state=42)

param_dist = {
    "n_estimators": [100, 200, 300, 500],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "max_depth": [2, 3, 4, 5],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "subsample": [0.7, 0.8, 0.9, 1.0],
    "max_features": ["sqrt", "log2", None]
}

search = RandomizedSearchCV(
    model,
    param_distributions=param_dist,
    n_iter=20,
    scoring="r2",
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

search.fit(X_train, y_train)

best_model = search.best_estimator_

y_pred = best_model.predict(X_test)

print("Best Params:", search.best_params_)
print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred))

Fitting 3 folds for each of 20 candidates, totalling 60 fits
Best Params: {'subsample': 0.9, 'n_estimators': 300, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': None, 'max_depth': 2, 'learning_rate': 0.2}
R2: 0.5825738514388402
MAE: 1.0054833163183838
RMSE: 2.290499255476399